# -*- coding: utf-8 -*-
"""forg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yCQdFLTMPTQLu6MgXTQa5iTHnGlcCaLS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from darts import TimeSeries as ts
from darts.utils.missing_values import fill_missing_values as fill_missing
from dateutil.relativedelta import relativedelta
from darts.models import ExponentialSmoothing, ARIMA, AutoARIMA, Prophet, Theta, FFT, NBEATSModel, NHiTSModel, TSMixerModel
import torch
torch.set_float32_matmul_precision('medium')
from darts.metrics import mape
import optuna
from tqdm import tqdm
from loguru import logger

def sharpe(ser):
    try:
        return ser.mean()/ser.std()
    except:
        return -1

def custom_sign(series, tolerance=1e-6):
  return np.where(np.abs(series) < tolerance, 0, np.sign(series))

class MyModeler:
  def __init__(self, data, modelfile, *, initialize_model = True, window = 100, horizon = 30, resample_rate = '1s', n_epochs = 5,  modeltype = NHiTSModel,  **modelparams):
    self.data = data
    self.model_file = modelfile
    self.window = window
    self.horizon = horizon
    self.n_epochs = n_epochs
    self.fcast = {}
    self.fcastdf = {}
    self.mape = {}
    self.datadict = {}
    self.netrets = {}
    self.grossrets = {}
    self.resample_rate= resample_rate
    self.modeltype = modeltype
    self.modelparams = modelparams

    self.init_model()

  def init_model(self):

    try:
    # Attempt to load existing model
      model_path = self.model_file
      self.model = self.modeltype.load(path=model_path)
    except FileNotFoundError:
      # If model does not exist, initialize a new one
      self.model = self.modeltype(
          input_chunk_length=self.window,
          output_chunk_length=2 * self.horizon,
          random_state=42,
          n_epochs=self.n_epochs,
          **self.modelparams,
         #num_workers = 15
      )

  def day_fit(self, *, data = None, theday = None):
    if data is None:
      data = self.data
    if theday is not None:
      subdata = data[data.index.normalize() == pd.to_datetime(theday)]
    else:
      subdata = data
    targetts  = ts.from_dataframe(subdata, freq = self.resample_rate)


    #if os.path.exists(self.modelfile + '.ckpt'):
    # self.model = NHiTSModel.load_from_checkpoint(self.modelfile + '.ckpt')
    #self.model = NHiTSModel.load(self.modelfile)
    self.model.fit(targetts, verbose=True)
    self.model.save(self.model_file)

  def day_predict(self, *, data = None, theday = None):
    if data is None:
      data = self.data
    if theday is not None:
      subdata = data[data.index.normalize() == pd.to_datetime(theday)]
    else:
      subdata = data
    targetts  = ts.from_dataframe(subdata, freq = self.resample_rate)
    historical_fcast = self.model.historical_forecasts(
         targetts,
         #past_covariates = [testc],
         retrain=False, verbose=True,
        )
    fcast_mape = mape(historical_fcast, targetts)
    return historical_fcast, fcast_mape

  @logger.catch
  def fit_span(self, beg_day = None, end_day = None):
    if beg_day is None:
      if end_day is None:
        subdata = self.data
      else:
        subdata = self.data.loc[:end_day]
    else:
      if end_day is None:
        subdata = self.data.loc[beg_day:]
      else:
        subdata = self.data.loc[beg_day:end_day]

    for d, df in subdata.groupby(subdata.index.date):
      logger.info(d)
      self.datadict[d] = subdata
      self.day_fit(data = df)

  @logger.catch
  def pred_span(self, beg_day = None, end_day = None, do_pl = False, **kwargs):
    if beg_day is None:
      if end_day is None:
        subdata = self.data
      else:
        subdata = self.data.loc[:end_day]
    else:
      if end_day is None:
        subdata = self.data.loc[beg_day:]
      else:
        subdata = self.data.loc[beg_day:end_day]


    for d, df in subdata.groupby(subdata.index.date):
      logger.info(d)
      self.datadict[d] = subdata
      f, m = self.day_predict(data = df)
      self.fcast[d] = f
      fdf = f.univariate_component(0).pd_dataframe()
      self.fcastdf[d] = fdf
      self.mape[d] = m
      if do_pl:
        self.do_pl(d, **kwargs)

  def do_pl(self, d, tolerance, tcosts):
    forecast_df = self.fcastdf[d]
    actual_df = self.datadict[d]
    # Assuming `actual_df` and `forecast_df` are your DataFrame variables
    actual_df.index = actual_df.index.tz_localize(None)  # Remove timezone, making it timezone-naive
    forecast_df.index = forecast_df.index.tz_localize(None)  # Remove timezone, making it timezone-naive

    custom_df = forecast_df.diff(self.horizon).apply(lambda x: custom_sign(x, tolerance))
    investment_returns = actual_df.diff(self.horizon) * custom_df/self.horizon
    investment_returns.dropna(inplace=True)
    net_returns = investment_returns - (tcosts / self.horizon) * (investment_returns != 0.0)
    total_netto = net_returns.sum()/self.horizon
    total_brutto = investment_returns.sum()/self.horizon

    self.netrets[d] = total_netto
    self.grossrets[d] = total_brutto



def do_pl(forecast_df, actual_df, tolerance, tcosts, horizon = 200):
    # Assuming `actual_df` and `forecast_df` are your DataFrame variables
    actual_df.index = actual_df.index.tz_localize(None)  # Remove timezone, making it timezone-naive
    forecast_df.index = forecast_df.index.tz_localize(None)  # Remove timezone, making it timezone-naive

    custom_df = forecast_df.diff(horizon).apply(lambda x: custom_sign(x, tolerance))
    investment_returns = actual_df.diff(horizon) * custom_df/horizon
    investment_returns.dropna(inplace=True)
    net_returns = investment_returns - (tcosts / horizon) * (investment_returns != 0.0)
    total_netto = net_returns.sum()/horizon
    total_brutto = investment_returns.sum()/horizon
    num_trades = len(custom_df[custom_df[custom_df.columns[0]]!=0])
    return total_netto, total_brutto, num_trades



def prep_indian_data(df):
  df.set_index('DateTime', inplace=True)
  df.sort_index(inplace = True)
  df_restricted = df.between_time('10:00', '15:00')
  df_restricted["LogBuyPrice" ]= np.log(df_restricted.BuyPrice)
  df_restricted["LogSellPrice"] = np.log(df_restricted.SellPrice)
  df_restricted["Spread"] = df_restricted.LogSellPrice - df_restricted.LogBuyPrice
  df2 = df_restricted.LogBuyPrice.resample('1s').ohlc()
  df3 = df_restricted.LogSellPrice.resample('1s').ohlc()
  return df2.close, df3.close

from polygon import RESTClient
from dateutil.relativedelta import relativedelta

client = RESTClient(pk)

import pandas as pd
import pandas_market_calendars as mcal

def fetch_full_trading_days(start_date, end_date, market='NYSE'):
    # Get the calendar for the specified market
    nyse_calendar = mcal.get_calendar(market)

    # Get the full schedule for the specified date range
    full_schedule = nyse_calendar.schedule(start_date=start_date, end_date=end_date)

    # Filter for full trading days, assuming NYSE standard hours are 9:30 to 16:00 in its local time
    full_days = full_schedule[
        (full_schedule.market_open.dt.tz_convert('America/New_York').dt.time == pd.Timestamp('09:30:00').time()) &
        (full_schedule.market_close.dt.tz_convert('America/New_York').dt.time == pd.Timestamp('16:00:00').time())
    ]

    return full_days.index.date

def is_full_trading_day(row):
        return (row['market_open'].tz_localize(None).time() == market_open_time.time() and
                row['market_close'].tz_localize(None).time() == market_close_time.time())

import pandas as pd

@logger.catch
def polygonprocess(ticker, start_date, end_date, freq="minute", do_log=True, market='NYSE'):
    if market == 'NYSE':
        good_dates = set(fetch_full_trading_days(start_date, end_date, market='NYSE'))
    else:
        good_dates = None

    start_date = pd.to_datetime(start_date)
    end_date = pd.to_datetime(end_date)
    datalist = []

    while start_date <= end_date:

        if good_dates is not None and start_date.date() not in good_dates:
            start_date += relativedelta(days=1)
            continue
        logger.info(start_date)

        start_str = start_date.strftime('%Y-%m-%d')
        end_str = (start_date + relativedelta(days=1)).strftime('%Y-%m-%d')

        try:
            bars = client.get_aggs(ticker=ticker, multiplier=1, timespan=freq, from_=start_str, to=end_str, limit=50000)
            df = pd.DataFrame(bars)
            datalist.append(df)
            start_date += relativedelta(days=1)
        except:
            start_date += relativedelta(days=1)

    datadf = pd.concat(datalist).drop_duplicates()
    datadf.timestamp = pd.to_datetime(datadf.timestamp, unit='ms', utc=True)
    datadf.timestamp = datadf.timestamp.dt.tz_convert('America/New_York')
    datadf = datadf.rename(columns={'open': 'Open', 'high': 'High', 'low': 'Low', 'close': 'Close', 'volume': 'Volume'})
    datadf.set_index('timestamp', inplace=True)

    dflist = []
    for d, df in datadf.groupby(datadf.index.date):
        tmp = df.resample('1s').ffill()
        dflist.append(tmp)
    newdata = pd.concat(dflist)

    if do_log:
        newdata['Close'] = np.log(newdata['Close'])

    # Filter records to only include those between 10:00 and 16:00 NY time, after ffill
    newdata = newdata.between_time('10:00', '16:00')

    # Handle potential duplicates
    if newdata.index.duplicated().any():
        newdata = newdata.groupby(newdata.index).last()

    return newdata[['Close']]

qqqdf = polygonprocess("QQQ", '2020-12-01', '2024-08-12', freq='second')

mymod5 = MyModeler(qqqdf, modelfile = 'qqqmod_NHiTS_11.pth', window = 200, horizon=60, modeltype = NHiTSModel, save_checkpoints = True, force_reset = True)

mymod5.fit_span(end_day = '2023-12-15')

mymod5.pred_span(do_pl=True, beg_day = '2024-01-01', end_day='2024-08-10',tolerance = 0.001, tcosts = 0.00005)

2+2

mymod5.netrets

netdf = pd.DataFrame(mymod5.netrets).T.sort_index()

netdf

netdf.describe()

netdf.Close.cumsum().plot()

sharpe(netdf)

mymod6 = MyModeler(qqqdf, modelfile = 'qqqmod_NHiTS_14.pth', window = 600, horizon=150, modeltype = NHiTSModel, save_checkpoints = True, force_reset = True)

mymod6.fit_span(beg_day = '2023-11-15', end_day = '2023-12-30')

mymod6.pred_span(do_pl=True, beg_day = '2024-01-01', end_day='2024-08-10',tolerance = 0.001, tcosts = 0.00005)

netdf2 = pd.DataFrame(mymod6.netrets).T.sort_index()

netdf2

"""netdf2.describe()"""

netdf2.describe()

netdf2.Close.cumsum().plot()

netdf2["NoAdj"] = netdf2.Close * 100

import quantstats as qs

qs.extend_pandas()

qs.reports.html(netdf2.NoAdj, output = "qqq.html")

# Commented out IPython magic to ensure Python compatibility.
# %ls

netdf2.NoAdj

netdf2.info()

netdf2.index = pd.to_datetime(netdf2.index)

qs.reports.full(netdf2.NoAdj)

mymod7 = MyModeler(qqqdf, modelfile = 'nftmod_NHiTS_1.pth', window = 600, horizon=150, modeltype = NHiTSModel, save_checkpoints = True, force_reset = True)

mymod7.fit_span(beg_day = "2024-05-02", end_day = "2024-05-10")

torch.cuda.empty_cache()

